virtualbox_vm.node: Creating...
  cpus:                                     "" => "4"
  image:                                    "" => "./terraform.d/images//xenial-server-cloudimg-amd64-vagrant.box"
  memory:                                   "" => "1.0 gib"
  name:                                     "" => "Ubuntu Server"
  network_adapter.#:                        "" => "1"
  network_adapter.0.device:                 "" => "IntelPro1000MTServer"
  network_adapter.0.host_interface:         "" => "p4p1"
  network_adapter.0.ipv4_address:           "" => "<computed>"
  network_adapter.0.ipv4_address_available: "" => "<computed>"
  network_adapter.0.mac_address:            "" => "<computed>"
  network_adapter.0.status:                 "" => "<computed>"
  network_adapter.0.type:                   "" => "bridged"
  status:                                   "" => "running"
  url:                                      "" => "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"

Error: Error applying plan:

1 error(s) occurred:

* virtualbox_vm.node: 1 error(s) occurred:

* virtualbox_vm.node: machine already exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


Exit code:
1
